---
abstract: 'Validates SPF text string'
author:
  - 'Anton Gerasimov <chim@cpan.org>'
build_requires:
  File::Spec: '0'
  File::Temp: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0'
  Test::Pod: '0.98'
  Test::Spec: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Validate-SPF
no_index:
  directory:
    - t
    - xt
    - eg
    - examples
    - corpus
  namespace:
    - t::lib
  package:
    - DB
provides:
  Parse::Yapp::Driver:
    file: lib/Validate/SPF/Parser.pm
    version: '0.002'
  Validate::SPF:
    file: lib/Validate/SPF.pm
    version: '0.002'
  Validate::SPF::Parser:
    file: lib/Validate/SPF/Parser.pm
    version: '0.002'
requires:
  Exporter: '0'
  Regexp::Common: '0'
  perl: '5.008009'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/Wu-Wu/Validate-SPF/issues
  homepage: https://metacpan.org/release/Validate-SPF
  repository: git://github.com/Wu-Wu/Validate-SPF.git
version: '0.002'
x_authority: cpan:CHIM
